"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../components/AppShell";
import { browserAccessToken, browserRole, listOrders, listProviderOffers } from "../lib/api";

export default function PortfolioPage(){
 const[token,setToken]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[stats,setStats]=useState<{total:number;active:number;completed:number;cancelled:number;offers?:number}|null>(null);
 async function load(){const access=browserAccessToken();setToken(access);if(!access){setLoading(false);return;}setLoading(true);setError("");try{const orders=(await listOrders(access)).orders;const active=orders.filter(o=>!["COMPLETED","DELIVERED","CANCELLED","EXPIRED","FAILED"].includes(o.status)).length;const completed=orders.filter(o=>["COMPLETED","DELIVERED"].includes(o.status)).length;const cancelled=orders.filter(o=>["CANCELLED","EXPIRED","FAILED"].includes(o.status)).length;let offers: number|undefined; if(["DRIVER","SERVICE_PROVIDER"].includes(browserRole()??"")){offers=(await listProviderOffers(access)).offers.length;}setStats({total:orders.length,active,completed,cancelled,offers});}catch(e){setError(e instanceof Error?e.message:"Portföy yüklenemedi.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 return <AppShell title="Portföy" kicker="GERÇEK HESAP İSTATİSTİKLERİ">{!token&&!loading?<section className="yl-card yl-empty"><strong>Portföy için giriş yap</strong><p>İstatistikler yalnızca gerçek hesap verilerinden hesaplanır.</p><Link href="/profile" className="yl-btn" style={{marginTop:14}}>Giriş yap</Link></section>:loading?<div className="yl-card yl-loading">Portföy hesaplanıyor…</div>:error?<p className="yl-error">{error} <button className="yl-btn-secondary" onClick={()=>void load()}>Tekrar dene</button></p>:stats&&<><section className="yl-grid-4"><div className="yl-card yl-stat"><strong>{stats.total}</strong><span>Toplam ilan</span></div><div className="yl-card yl-stat"><strong>{stats.active}</strong><span>Aktif ilan</span></div><div className="yl-card yl-stat"><strong>{stats.completed}</strong><span>Tamamlanan</span></div><div className="yl-card yl-stat"><strong>{stats.offers??"-"}</strong><span>Verilen teklifler</span></div></section><section className="yl-card" style={{marginTop:14}}><h2 style={{marginTop:0}}>İşlem özeti</h2><p className="yl-muted">İptal / kapanan işlem: <strong>{stats.cancelled}</strong></p><p className="yl-info">Toplam taşıma mesafesi ve gelir için kesinleşmiş mesafe ile ödeme/tahsilat tabloları henüz bulunmuyor. Bu nedenle burada insanlığın sevdiği o dekoratif ama sahte grafiklerden üretmiyoruz.</p><div className="yl-form-row"><Link className="yl-btn" href="/orders">İlanları gör</Link><Link className="yl-btn-secondary" href="/provider">Taşıyıcı merkezi</Link></div></section></>}</AppShell>;
}
