"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../components/AppShell";
import { browserAccessToken, changePassword, clearBrowserSession, deactivateAccount, getProfile, login, logout, register, updateProfile, type ProfileUser } from "../lib/api";

export default function ProfilePage() {
  const [token,setToken]=useState<string|null>(null),[profile,setProfile]=useState<ProfileUser|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const [authMode,setAuthMode]=useState<"login"|"register">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState("");
  const [editing,setEditing]=useState(false),[editFirst,setEditFirst]=useState(""),[editLast,setEditLast]=useState(""),[editPhone,setEditPhone]=useState(""),[company,setCompany]=useState("");
  const [passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState("");

  async function load(access?:string|null){const next=access??browserAccessToken();setToken(next);if(!next){setProfile(null);setLoading(false);return;}setLoading(true);try{const result=await getProfile(next);setProfile(result.user);setEditFirst(result.user.firstName);setEditLast(result.user.lastName);setEditPhone(result.user.phone??"");setCompany(result.user.companyProfile?.companyName??"");}catch(e){setMessage(e instanceof Error?e.message:"Profil yüklenemedi.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);

  async function authSubmit(e:FormEvent){e.preventDefault();setMessage("");try{if(authMode==="register"){if(!firstName.trim()||!lastName.trim())throw new Error("Ad ve soyad gerekli.");await register({email:email.trim(),password,firstName:firstName.trim(),lastName:lastName.trim()});}const result=await login(email.trim(),password);setToken(result.accessToken);await load(result.accessToken);}catch(err){setMessage(err instanceof Error?err.message:"Giriş işlemi başarısız.");}}
  async function saveProfile(e:FormEvent){e.preventDefault();if(!token)return;try{const result=await updateProfile(token,{firstName:editFirst.trim(),lastName:editLast.trim(),phone:editPhone.trim()||null,...(company.trim()?{company:{companyName:company.trim()}}:{})});setProfile(result.user);setEditing(false);setMessage("Profil güncellendi.");}catch(err){setMessage(err instanceof Error?err.message:"Profil güncellenemedi.");}}
  async function doLogout(){if(!token)return;const refresh=localStorage.getItem("yuklab_refresh_token");try{if(refresh)await logout(token,refresh);else clearBrowserSession();}finally{setToken(null);setProfile(null);}}
  async function doPassword(e:FormEvent){e.preventDefault();if(!token)return;if(newPassword.length<8){setMessage("Yeni şifre en az 8 karakter olmalı.");return;}try{await changePassword(token,currentPassword,newPassword);clearBrowserSession();setToken(null);setProfile(null);setPasswordOpen(false);setMessage("Şifre değiştirildi. Güvenlik nedeniyle yeniden giriş yap.");}catch(err){setMessage(err instanceof Error?err.message:"Şifre değiştirilemedi.");}}
  async function deactivate(){if(!token||!confirm("Hesabın devre dışı bırakılacak ve kişisel bilgiler temizlenecek. Devam edilsin mi?"))return;try{await deactivateAccount(token);clearBrowserSession();setToken(null);setProfile(null);setMessage("Hesap devre dışı bırakıldı.");}catch(err){setMessage(err instanceof Error?err.message:"Hesap devre dışı bırakılamadı.");}}

  return <AppShell title="Profil" kicker="HESAP VE AYARLAR">
    {message&&<p className={message.includes("güncellendi")||message.includes("değiştirildi")||message.includes("bırakıldı")?"yl-success":"yl-info"}>{message}</p>}
    {loading?<div className="yl-card yl-loading">Profil yükleniyor…</div>:!token||!profile?<div className="yl-stack"><section className="yl-card"><div className="yl-profile-head"><span className="yl-profile-avatar">○</span><div><h2>Hesabına giriş yap</h2><p>İlan verebilir, teklif alabilir ve tüm özelliklerden yararlanabilirsin.</p></div></div><form className="yl-form" onSubmit={authSubmit} style={{marginTop:18}}>{authMode==="register"&&<div className="yl-form-row"><label>Ad<input value={firstName} onChange={e=>setFirstName(e.target.value)} required/></label><label>Soyad<input value={lastName} onChange={e=>setLastName(e.target.value)} required/></label></div>}<label>E-posta<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Şifre<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="yl-btn" type="submit">{authMode==="login"?"Giriş yap":"Kayıt ol ve giriş yap"}</button><button className="yl-btn-secondary" type="button" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Yeni hesap oluştur":"Mevcut hesabımla giriş yap"}</button></form></section><section className="yl-card"><div className="yl-menu-list"><Link href="/notifications">Bildirimler <span>→</span></Link><Link href="/">Panel <span>→</span></Link></div></section></div>:<div className="yl-stack">
      <section className="yl-card"><div className="yl-profile-head"><span className="yl-profile-avatar">○</span><div><h2>{profile.firstName} {profile.lastName}</h2><p>{profile.companyProfile?.companyName||profile.email||profile.phone||"YükLab kullanıcısı"}</p><span className="yl-badge" style={{marginTop:8}}>{profile.role}</span></div></div><button className="yl-btn-secondary" onClick={()=>setEditing(!editing)} style={{marginTop:16}}>Profili düzenle</button></section>
      {editing&&<form className="yl-card yl-form" onSubmit={saveProfile}><h2 style={{margin:0}}>Kişisel bilgiler</h2><div className="yl-form-row"><label>Ad<input value={editFirst} onChange={e=>setEditFirst(e.target.value)} required/></label><label>Soyad<input value={editLast} onChange={e=>setEditLast(e.target.value)} required/></label></div><label>Telefon<input value={editPhone} onChange={e=>setEditPhone(e.target.value)}/></label><label>Firma adı<input value={company} onChange={e=>setCompany(e.target.value)}/></label><button className="yl-btn" type="submit">Kaydet</button></form>}
      <section className="yl-card"><h3 style={{marginTop:0}}>Hesap ayarları</h3><div className="yl-menu-list"><Link href="/orders">İlanlarım <span>→</span></Link><Link href="/provider">Araçlarım ve tekliflerim <span>→</span></Link><Link href="/portfolio">Portföyüm <span>→</span></Link><Link href="/notifications">Bildirimler <span>→</span></Link><button onClick={()=>setPasswordOpen(!passwordOpen)}>Şifre değiştir <span>→</span></button></div></section>
      {passwordOpen&&<form className="yl-card yl-form" onSubmit={doPassword}><h2 style={{margin:0}}>Şifre değiştir</h2><label>Mevcut şifre<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/></label><label>Yeni şifre<input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label><button className="yl-btn" type="submit">Şifreyi değiştir</button></form>}
      <section className="yl-card"><button className="yl-btn-secondary" onClick={()=>void doLogout()} style={{width:"100%"}}>Çıkış yap</button><button className="yl-btn-danger" onClick={()=>void deactivate()} style={{width:"100%",marginTop:9}}>Hesabı devre dışı bırak</button></section>
    </div>}
  </AppShell>;
}
