"use client";

import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../components/AppShell";
import { becomeProvider, browserAccessToken, createOrder, createVehicle, updateProfile, updateWorkRegions } from "../lib/api";

type Mode = "menu" | "load" | "text" | "carrier";
const vehicles = ["ANY","MOTORCYCLE","VAN","TRUCK","KIRKAYAK","TIR","TOW_TRUCK","REFRIGERATED","DUMP_TRUCK","FLATBED"];

export default function CreatePage() {
  const [mode,setMode]=useState<Mode>("menu");
  const [token,setToken]=useState<string|null>(null);
  const [message,setMessage]=useState("");
  const [preview,setPreview]=useState(false);
  const [pickup,setPickup]=useState(""),[delivery,setDelivery]=useState(""),[loadType,setLoadType]=useState(""),[weight,setWeight]=useState(""),[dimensions,setDimensions]=useState(""),[vehicle,setVehicle]=useState("ANY"),[pickupDate,setPickupDate]=useState(""),[deliveryDate,setDeliveryDate]=useState(""),[budget,setBudget]=useState(""),[notes,setNotes]=useState("");
  const [textDraft,setTextDraft]=useState("");
  const [providerType,setProviderType]=useState<"DRIVER"|"SERVICE_PROVIDER">("DRIVER"),[category,setCategory]=useState("GENERAL"),[company,setCompany]=useState(""),[city,setCity]=useState(""),[district,setDistrict]=useState(""),[radius,setRadius]=useState("50"),[carrierVehicle,setCarrierVehicle]=useState("TRUCK"),[plate,setPlate]=useState(""),[capacity,setCapacity]=useState("");

  useEffect(()=>{const access=browserAccessToken();setToken(access);try{const draft=JSON.parse(localStorage.getItem("yuklab_order_draft")||"null");if(draft){setPickup(draft.pickup||"");setDelivery(draft.delivery||"");setLoadType(draft.loadType||"");setWeight(draft.weight||"");setDimensions(draft.dimensions||"");setVehicle(draft.vehicle||"ANY");setPickupDate(draft.pickupDate||"");setDeliveryDate(draft.deliveryDate||"");setBudget(draft.budget||"");setNotes(draft.notes||"");}setTextDraft(localStorage.getItem("yuklab_text_draft")||"");}catch{}},[]);

  const draft={pickup,delivery,loadType,weight,dimensions,vehicle,pickupDate,deliveryDate,budget,notes};
  function validate(){if(!pickup.trim())return"Çıkış noktası gerekli.";if(!delivery.trim())return"Varış noktası gerekli.";if(!loadType.trim())return"Yük türü gerekli.";if(!weight||Number(weight)<=0)return"Ağırlık sıfırdan büyük olmalı.";if(!pickupDate)return"Alım tarihi gerekli.";if(deliveryDate&&deliveryDate<pickupDate)return"Teslim tarihi alım tarihinden önce olamaz.";if(budget&&(!Number.isFinite(Number(budget))||Number(budget)<0))return"Fiyat geçersiz.";return"";}
  function saveDraft(){localStorage.setItem("yuklab_order_draft",JSON.stringify(draft));setMessage("Taslak bu tarayıcıda kaydedildi.");}
  async function publish(){if(!token){setMessage("İlan yayınlamak için profil ekranından giriş yap.");return;}const issue=validate();if(issue){setMessage(issue);return;}try{await createOrder(token,{serviceType:"LOAD",pickupAddress:pickup.trim(),deliveryAddress:delivery.trim(),scheduledAt:`${pickupDate}T09:00:00+03:00`,budgetMinor:budget?Math.round(Number(budget)*100):undefined,currency:"TRY",payload:{loadType:loadType.trim(),weightKg:Number(weight),vehicleType:vehicle,notes:notes.trim(),dimensions,deliveryDate}});localStorage.removeItem("yuklab_order_draft");setMessage("İlan başarıyla yayınlandı.");setPreview(false);}catch(e){setMessage(e instanceof Error?e.message:"İlan yayınlanamadı.");}}
  async function carrierSubmit(e:FormEvent){e.preventDefault();if(!token){setMessage("Taşıyıcı hesabı oluşturmak için önce giriş yap.");return;}if(!city.trim()||!plate.trim()){setMessage("Çalışma şehri ve plaka zorunlu.");return;}const km=Number(radius);if(!Number.isFinite(km)||km<1||km>500){setMessage("Hizmet yarıçapı 1–500 km arasında olmalı.");return;}try{if(company.trim())await updateProfile(token,{company:{companyName:company.trim()}});await becomeProvider(token,category.trim()||"GENERAL",providerType);await updateWorkRegions(token,[{country:"TR",city:city.trim(),district:district.trim()||null,radiusKm:km}]);await createVehicle(token,{type:carrierVehicle,plateNumber:plate.trim(),capacityKg:capacity?Number(capacity):undefined});setMessage("Taşıyıcı hesabı, çalışma bölgesi ve araç kaydı oluşturuldu.");}catch(err){setMessage(err instanceof Error?err.message:"Taşıyıcı hesabı oluşturulamadı.");}}

  return <AppShell title="Yeni oluştur" kicker="YÜKLAB OLUŞTURMA MERKEZİ">
    {mode!=="menu"&&<button className="yl-btn-secondary" onClick={()=>{setMode("menu");setPreview(false);setMessage("");}} style={{marginBottom:14}}>← Seçeneklere dön</button>}
    {message&&<p className={message.includes("başarı")||message.includes("kaydedildi")||message.includes("oluşturuldu")?"yl-success":"yl-info"}>{message}</p>}
    {mode==="menu"&&<><div className="yl-section-head"><div><h2>Nasıl başlamak istersin?</h2><p>Yükünü veya aracını birkaç adımda ekle.</p></div></div><div className="yl-stack">
      <button className="yl-card yl-choice" onClick={()=>setMode("load")}><span className="yl-choice-icon">□</span><div><h3>Yük ilanı oluştur</h3><p>Güzergâh, yük ve fiyat bilgilerini girerek ilanını oluştur.</p></div><span className="yl-choice-arrow">→</span></button>
      <button className="yl-card yl-choice" onClick={()=>setMode("text")}><span className="yl-choice-icon">✧</span><div><h3>Metinden ilan hazırla</h3><p>LLM entegrasyonu yok. Metnini güvenli bir yerel taslak olarak sakla.</p></div><span className="yl-choice-arrow">→</span></button>
      <button className="yl-card yl-choice" onClick={()=>setMode("carrier")}><span className="yl-choice-icon">▣</span><div><h3>Taşıyıcı olmak istiyorum</h3><p>Çalışma bölgeni ve ilk aracını gerçek API ile kaydet.</p></div><span className="yl-choice-arrow">→</span></button>
    </div></>}

    {mode==="load"&&!preview&&<form className="yl-card yl-form" onSubmit={e=>{e.preventDefault();const issue=validate();if(issue)setMessage(issue);else{setMessage("");setPreview(true);}}}>
      <h2 style={{margin:0}}>Yük ilanı oluştur</h2><p className="yl-muted" style={{margin:0}}>Zorunlu alanları doldur, önizle ve yayınla.</p>
      <div className="yl-form-row"><label>Çıkış noktası *<input value={pickup} onChange={e=>setPickup(e.target.value)} required/></label><label>Varış noktası *<input value={delivery} onChange={e=>setDelivery(e.target.value)} required/></label></div>
      <div className="yl-form-row"><label>Yük türü *<input value={loadType} onChange={e=>setLoadType(e.target.value)} placeholder="Paletli ürün, mobilya…" required/></label><label>Ağırlık (kg) *<input type="number" min="0.1" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} required/></label></div>
      <div className="yl-form-row"><label>Ölçüler<input value={dimensions} onChange={e=>setDimensions(e.target.value)} placeholder="120×80×150 cm"/></label><label>Araç tipi<select value={vehicle} onChange={e=>setVehicle(e.target.value)}>{vehicles.map(v=><option key={v}>{v}</option>)}</select></label></div>
      <div className="yl-form-row"><label>Alım tarihi *<input type="date" value={pickupDate} onChange={e=>setPickupDate(e.target.value)} required/></label><label>Teslim tarihi<input type="date" value={deliveryDate} min={pickupDate||undefined} onChange={e=>setDeliveryDate(e.target.value)}/></label></div>
      <label>Fiyat / bütçe (₺)<input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>Açıklama<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>
      <p className="yl-info">Fotoğraf ve ek dosya depolama altyapısı henüz bağlı değil. Bu yüzden çalışmayan bir yükleme butonu sergilenmiyor.</p>
      <div className="yl-form-row"><button type="button" className="yl-btn-secondary" onClick={saveDraft}>Taslak kaydet</button><button className="yl-btn" type="submit">Önizle</button></div>
    </form>}
    {mode==="load"&&preview&&<section className="yl-card"><h2>İlan önizleme</h2><div className="yl-route"><div><strong>{pickup}</strong><small>Çıkış</small></div><span className="yl-route-arrow">→</span><div><strong>{delivery}</strong><small>Varış</small></div></div><div className="yl-order-meta" style={{marginTop:18}}><div><span>Yük</span><strong>{loadType}</strong></div><div><span>Ağırlık</span><strong>{weight} kg</strong></div><div><span>Alım</span><strong>{pickupDate}</strong></div><div><span>Fiyat</span><strong>{budget?`${budget} ₺`:"Teklif"}</strong></div></div><div className="yl-form-row" style={{marginTop:18}}><button className="yl-btn-secondary" onClick={()=>setPreview(false)}>Düzenlemeye dön</button><button className="yl-btn" onClick={()=>void publish()}>Yayınla</button></div></section>}

    {mode==="text"&&<section className="yl-card yl-form"><h2 style={{margin:0}}>Metinden ilan taslağı</h2><p className="yl-info">Gerçek bir LLM/backend entegrasyonu bulunmadığı için metin analiz edilmiş gibi gösterilmiyor. Burada yalnızca yerel taslak saklanır.</p><label>İlan metni<textarea value={textDraft} onChange={e=>setTextDraft(e.target.value)} placeholder="Kayseri'den Ankara'ya 2 ton paletli ürün…"/></label><button className="yl-btn" onClick={()=>{if(!textDraft.trim()){setMessage("Taslak metni boş olamaz.");return;}localStorage.setItem("yuklab_text_draft",textDraft.trim());setMessage("Metin taslağı kaydedildi.");}}>Taslağı kaydet</button></section>}

    {mode==="carrier"&&<form className="yl-card yl-form" onSubmit={carrierSubmit}><h2 style={{margin:0}}>Taşıyıcı hesabını hazırla</h2><div className="yl-form-row"><label>Hesap türü<select value={providerType} onChange={e=>setProviderType(e.target.value as "DRIVER"|"SERVICE_PROVIDER")}><option value="DRIVER">Sürücü / taşıyıcı</option><option value="SERVICE_PROVIDER">Hizmet sağlayıcı</option></select></label><label>Kategori<input value={category} onChange={e=>setCategory(e.target.value)}/></label></div><label>Firma adı<input value={company} onChange={e=>setCompany(e.target.value)}/></label><div className="yl-form-row"><label>Çalışma şehri *<input value={city} onChange={e=>setCity(e.target.value)} required/></label><label>İlçe<input value={district} onChange={e=>setDistrict(e.target.value)}/></label></div><div className="yl-form-row"><label>Hizmet yarıçapı (km)<input type="number" min="1" max="500" value={radius} onChange={e=>setRadius(e.target.value)}/></label><label>Araç tipi<select value={carrierVehicle} onChange={e=>setCarrierVehicle(e.target.value)}>{vehicles.filter(v=>v!=="ANY").map(v=><option key={v}>{v}</option>)}</select></label></div><div className="yl-form-row"><label>Plaka *<input value={plate} onChange={e=>setPlate(e.target.value)} required/></label><label>Kapasite (kg)<input type="number" min="0" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label></div><p className="yl-info">Belge modeli ve onay durumu backend'de mevcut, fakat gerçek dosya depolama/multipart yükleme servisi henüz bağlı değil. Belge yükleme sahte biçimde sunulmuyor.</p><button className="yl-btn" type="submit">Taşıyıcı hesabını oluştur</button></form>}
  </AppShell>;
}
